export const dropData = [
  {
    name: "And Then There Were Four",
    creator: "NBA Top Shot",
    collectionName: "NBA Top Shot",
    date: "July 14, 2021 13:00:00",
    url: "https://nbatopshot.com/listings/pack/3e30dfec-949c-4807-bd6c-3da61c3ce833",
    minPrice: 79,
    marketplace: "NBA Top Shot",
    category: "Sports",
  },
  {
    name: "test",
    creator: "test",
    collectionName: "test",
    date: "May 13, 2021 17:00:00",
    url: "test",
    minPrice: 0,
    marketplace: "test",
    category: "test",
  },
  {
    name: "YOU ONLY LOVED ME WHEN WE WERE HIGH COLLECTION by Marius Sperlich",
    creator: "Marius Sperlich",
    collectionName: "YOU ONLY LOVED ME WHEN WE WERE HIGH COLLECTION by Marius Sperlich",
    date: "May 14, 2021 14:30:00",
    url: "https://niftygateway.com/collections/mariusperlich",
    minPrice: 2500,
    marketplace: "Nifty Gateway",
    category: "Art",
  },
  {
    name: "YOU ONLY LOVED ME WHEN WE WERE HIGH COLLECTION Open Editions by Marius Sperlich",
    creator: "Marius Sperlich",
    collectionName: "YOU ONLY LOVED ME WHEN WE WERE HIGH COLLECTION Open Editions by Marius Sperlich",
    date: "May 14, 2021 15:00:00",
    url: "https://niftygateway.com/collections/mariusperlichopen",
    minPrice: 500,
    marketplace: "Nifty Gateway",
    category: "Art",
  },
  {
    name: "The 8",
    creator: "lushsux",
    collectionName: null,
    date: "May 16, 2021 18:00:00",
    url: "https://makersplace.com/lushsux/drops/the-eight/",
    minPrice: null,
    marketplace: "Makers Place",
    category: "Art",
  },
  {
    name: "Satoshi5",
    creator: "Bitcoin Origins",
    collectionName: "Bitcoin Origins",
    date: "May 13, 2021 15:00:00",
    url: "https://www.btcorigins.com/",
    minPrice: 0,
    marketplace: "Atomic Assets",
    category: "Trading Cards",
  },
  {
    name: "RISING STARS",
    creator: "NBA Top Shot",
    collectionName: "NBA Top Shot",
    date: "May 7, 2021 14:00:00",
    url: "https://www.nbatopshot.com/",
    minPrice: 199,
    marketplace: "NBA Top Shot",
    category: "Sports",
  },
];
